# Generated by Django 4.2.2 on 2024-01-15 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carspec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_brand', models.CharField(max_length=50)),
                ('car_model', models.CharField(max_length=100)),
                ('production_year', models.CharField(max_length=50)),
                ('mileage', models.FloatField()),
                ('color', models.CharField(default=None, max_length=50)),
                ('fuel_type', models.CharField(choices=[('Diesel', 'Diesel'), ('Super', 'Super')], max_length=20)),
                ('transmission_type', models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], max_length=20)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable')], max_length=100)),
                ('DV_Number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('other_name', models.CharField(default=None, max_length=100)),
                ('phone', models.CharField(max_length=14, unique=True)),
                ('client_Id_type', models.CharField(choices=[('Ghana Card', 'Ghana Card'), ('Voters ID', 'Voters ID'), ('NHIS', 'NHIS'), ('Driver License', 'Driver License')], max_length=100)),
                ('client_id', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='client_images')),
            ],
        ),
        migrations.CreateModel(
            name='Nothing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(max_length=1000)),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.carspec')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.client')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('Completed', 'Complete'), ('Reserved', 'Reserved'), ('Cancelled', 'Cancelled')], max_length=100)),
                ('car_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='api.carspec')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.client')),
            ],
        ),
    ]
