# Generated by Django 4.2.2 on 2024-01-07 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carspec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_brand', models.CharField(max_length=50)),
                ('car_model', models.CharField(max_length=100)),
                ('production_year', models.CharField(max_length=50)),
                ('car_body', models.CharField(max_length=18)),
                ('engine_type', models.CharField(max_length=100)),
                ('mileage', models.FloatField()),
                ('color', models.CharField(default=None, max_length=50)),
                ('fuel_type', models.CharField(choices=[('Diesel', 'Diesel'), ('Super', 'Super')], max_length=20)),
                ('transmission_type', models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], max_length=20)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('other_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=14, unique=True)),
                ('client_Id', models.CharField(choices=[('Ghana Card', 'Ghana Card'), ('Voters ID', 'Voters ID'), ('NHIS', 'NHIS'), ('Driver License', 'Driver License')], max_length=100)),
                ('address', models.SlugField()),
                ('photo', models.ImageField(upload_to='client_images')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('Completed', 'Complete'), ('Reserved', 'Reserved'), ('Cancelled', 'Cancelled')], max_length=100)),
                ('car_info', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.carspec')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.client')),
            ],
        ),
    ]
