# Generated by Django 4.2.2 on 2024-01-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='other_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
