# Generated by Django 4.2.2 on 2024-01-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carspec',
            name='DV_Number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
