# Generated by Django 4.2.2 on 2024-01-08 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_client_other_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carspec',
            old_name='status',
            new_name='avail_status',
        ),
    ]
