# Generated by Django 4.2.2 on 2024-01-08 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_status_carspec_avail_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carspec',
            old_name='avail_status',
            new_name='status',
        ),
    ]
