# Generated by Django 4.2.2 on 2024-01-08 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_avail_status_carspec_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='car_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking', to='api.carspec'),
        ),
    ]
