# Generated by Django 4.2.2 on 2024-01-08 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_booking_car_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='car_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='api.carspec'),
        ),
    ]
