# Generated by Django 4.2.2 on 2024-01-08 21:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_booking_car_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='carspec',
            name='DV_Number',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
