# Generated by Django 4.2.2 on 2024-01-08 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_carspec_dv_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carspec',
            name='car_body',
        ),
    ]
