# Generated by Django 4.2.2 on 2024-01-08 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_carspec_engine_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='car_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='api.carspec'),
        ),
    ]
