# Generated by Django 4.2.2 on 2024-01-08 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_client_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='car_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.carspec'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.client'),
        ),
    ]
